[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/paulmach/orb"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[prune]
  go-tests = true
  unused-packages = true
